personal_website/apps/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views


app_name = "accounts"

urlpatterns = [
    path(
        "profile",
        views.ProfileView.as_view(template_name="accounts/profile.html"),
        name="profile",
    ),
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]

personal_website/apps/contact/urls.py
from django.urls import path
from . import views

app_name = "contact"

urlpatterns = [
    # path("", views.contact, name=""),
    path("contact/", views.contact, name="contact_form")
]

personal_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("personal_website.apps.public.urls")),
    path("accounts/", include("personal_website.apps.accounts.urls")),
    path("contact/", include("personal_website.apps.contact.urls")),
]

personal_website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    # owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    # settings
    is_full_name_displayed = models.BooleanField(default=True)

    # details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    persona = models.ForeignKey(
        UserPersona, on_delete=models.SET_NULL, blank=True, null=True
    )
    interest = models.ManyToManyField(UserInterest, blank=True)

personal_website/apps/contact/models.py
from django.db import models

# Create your models here.

personal_website/apps/contact/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Name"}),
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Email"}
        ),
    )
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Message", "rows": 5}
        ),
    )

personal_website/apps/accounts/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

personal_website/apps/contact/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.core.mail import send_mail
from .forms import ContactForm
from personal_website import settings
import bleach


def contact(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        form = ContactForm()

    elif request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = bleach.cleaned_data["name"]
            email = bleach.cleaned_data["email"]
            message = bleach.cleaned_data["message"]
            send_mail(f"{name} sent an email", message, email, [settings.DEFAULT_FROM_EMAIL])
            return render(request, "contact.html", {"form": form, "success": True}) 
    else: 
        raise NotImplementedError
    
    return render(request, "contact.html", {"form": form})

# def contact_form(request: HttpRequest) -> HttpResponse:
#     return render(request, 'contact.html')  # Return the rendered response

personal_website/templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<h1>
    About
</h1>
{% endblock %}

personal_website/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<h2> Login </h2>
<form method = "post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Login</button>
</form>
{% endblock %}

personal_website/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<h1>
    {{ user.get_full_name }} @{{user.username}}
</h1>

{% with profile=user.profile %}
    {% if profile %}
        <h2>
            {{ profile.persona|default:"" }}
        </h2>
        <div>
            {{ profile.bio|default:"" }}
        </div>
        <div>
            {% with website=profile.website|default:"" %}
                <a href="{{'website'}}">{{ website }}</a>
            {% endwith %}
        </div>
        <br/>
        <div>
            Interest:
            {% for interest in profile.interest.all %}
                <span>
                    {{ interest.name }}{% if not forloop.last %}. {% endif %}
                </span>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}

{% endblock %}

personal_website/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Adam Musiał {% endblock %}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
  </head>
  <body>
    {% include 'navbar.html' %}
    <main id="main">
        {% block content %}
        {% endblock %}
    </main>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'theme/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
       
  </body>
</html>

personal_website/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<section>
    <h1>Contact US</h1>
    <div class="row justify-content-center">
        <div class="col-lg-8 col-xl-7">

            {% if success %}
            <div class="alert alert-success" role="alert">
                Your message was send! Check your invox for a response!
            </div>
            {% endif %}


            <form id="contactForm" name="sentMessage" method="post" novalidate="novalidate">
                {% csrf_token %}

                {% if form.non_field_errors %}

                <div class="alert alert-danger" role="alert">
                    {{form.non_field_errors}}
                </div>

                {% endif %}

                {% for field in form %}
                    <div class="form-floating mb-3">
                        {{ field.label_tag }}
                        {{ field }}
                        {% for error in field.errors %}
                            <p class="help-block text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}
                <br />
                <div class="form-group">
                    <button class="btn btn-primary btn-xl" id="submitButton" type="submit">Send</button>
                </div>
            </form> <!-- Closing form tag moved inside the div -->
            <div class="d-none" id="submitErrorMessage">
                <div class="text-center text-danger mb-3">Error sending message!</div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

personal_website/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}

<!-- <img class="img-fluid rounded mb-5" src="{% static 'theme/assets/img/portfolio/cabin.png' %}" alt="..." /> -->
<header class="masthead text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <!-- <img class="masthead-avatar mb-5" src="{%static 'theme/assets/img/avataaars.svg'%}" alt="..." /> -->
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Never stop exploring</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0"></p>
    </div>
</header>


<h1>
    Template Homepage
</h1>
{% endblock %}

personal_website/templates/navbar.html
{% url 'public:index' as index_url %}
{% url 'public:about' as about_url %}
{% url 'contact:contact_form' as contact_url %}



<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{{ index_url }}">Adam Musiał</a>
        <button class="navbar-toggler text-uppercase font-weight-bold hs-bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 {% if request.path == index_url %} active {% endif %}" href="{{ index_url }}">Home</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 {% if request.path == about_url %} active {% endif %}" href="{{ about_url }}">About</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 {% if request.path == contact_url %} active {% endif %}" href="{{ contact_url }}">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>


<!-- <div>
    {% url 'public:index' as index_url %}
    <span {% if request.path == index_url %} Home {% else %}><a href="{{ index_url }}">Home</a>{% endif %}</span>
    {% url 'public:about' as about_url %}
    <span {% if request.path == about_url %} About {% else %}><a href="{{ about_url }}">About</a>{% endif %}</span>
    {% url 'contact:contact' as contact_url %}
    <span {% if request.path == contact_url %} Contact {% else %}><a href="{{ contact_url }}">Contact</a>{% endif %}</span>

    <span style="float:right">
        {% if user.is_authenticated %}
            {% url 'accounts:profile' as profile_url %}
            <span>Hi {% if request.path == profile_url %}{{user.username}}{% else %}<a href ="{{profile_url}}">{{user.username}}</a>{% endif %}</span>
            <span><a href ="{% url 'accounts:logout' %}">Logout</a></span>
        {% else %}
            <span><a href ="{% url 'accounts:login' %}">Login</a></span>
        {% endif %}
    </span>
</div> -->